spring.application.name=LifeChoosesUServer
server.port=8080
spring.datasource.url=jdbc:postgresql://db.puvgcawkuyhioxarckwg.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=lcudatabaseHh$
spring.jpa.hibernate.ddl-auto=update
server.servlet.session.cookie.name=LCU_SESSION_COOKIE
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=true
spring.jpa.open-in-view=true