spring.application.name=LifeChoosesUServer
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/LifeChoosesU
spring.datasource.username=dida
spring.datasource.password=2425
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect